# Set bundle path to ./gems
bundle_path "gems"

# dependencies are generated using a strict version, don't forget to edit the dependency versions when upgrading.
merb_gems_version = "1.1"

# If you did disable json for Merb, comment out this line.
# If you want use json gem just change it.
# Don't use json gem version lower than 1.1.7! Older versions has security bug!
gem "json_pure", ">= 1.1.7", :require_as => "json"
gem "merb-core", merb_gems_version
gem "merb-colorful-logger"




